routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('app');
});
// Route::get('/dashboard', 'Backend\DashboardController@index')->name('dashboard');

Route::group(['middleware' => ['auth']], function() {
    Route::prefix('master')->group(function () {
        Route::get('dashboard', 'Backend\DashboardController@index')->name('dashboard');
        Route::resource('user', 'Backend\AdminController');
        Route::resource('courrier', 'Backend\CourrierController');
        Route::resource('supplier', 'Backend\SupplierController');
        Route::resource('product', 'Backend\ProductController');
        Route::resource('recipe', 'Backend\RecipeController');
        Route::resource('ingredients', 'Backend\IngredientController');
    });
});

require __DIR__.'/auth.php';

app/Models/Ingredients.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ingredients extends Model
{
    use HasFactory;
    protected $table = 'ingredients';
}

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use File;

class AdminController extends Controller
{
    private $param;
    public function __construct()
    {
        $this->param['title'] = 'Admin';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->param['subtitle'] = 'List Admin';
        $this->param['data'] = User::select('id', 'name', 'username', 'profile_photo')->get();
        $this->param['top_button'] = route('user.create');

        return view('backend.user.index', $this->param);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->param['subtitle'] = 'Tambah Admin';
        $this->param['top_button'] = route('user.index');

        return view('backend.user.create', $this->param);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            [
                'nama_lengkap' => 'required|min:6|max:50',
                'username' => 'required|min:4|max:30|unique:users,username',
                'password' => 'required|min:6|confirmed'
            ],
            [
                'required' => ':attribute harus diisi.',
                'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                'username.min' => 'Minimal panjang karakter 4.',
                'username.max' => 'Maksimal panjang karakter 30.',
                'password.min' => 'Minimal panjang karakter 6.',
                'confirmed' => 'Password tidak sesuai.',
                'username.unique' => ':attribute telah terdaftar.'
            ],
            [
                'nama_lengkap' => 'Nama lengkap',
                'username' => 'Username',
                'password' => 'Password',
                'password_confirmation' => 'Konfirmasi password'
            ]
        );

        try{
            $newAdmin = new User;
            $newAdmin->name = $request->get('nama_lengkap');
            $newAdmin->username = $request->get('username');
            $newAdmin->password = \Hash::make($request->get('password'));
            if($request->file('photo_profile') != null) {
                $folder = 'upload/admin/'.$request->get('username');
                $file = $request->file('photo_profile');
                $filename = date('YmdHis').$file->getClientOriginalName();
                // Get canonicalized absolute pathname
                $path = realpath($folder);

                // If it exist, check if it's a directory
                if(!($path !== true AND is_dir($path)))
                {
                    // Path/folder does not exist then create a new folder
                    mkdir($folder, 0755, true);
                }
                if($file->move($folder, $filename)) {
                    $newAdmin->profile_photo = $folder.'/'.$filename;
                }
            }
            $newAdmin->save();
            return redirect('master/user')->withStatus('Berhasil menambah data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
            $this->param['subtitle'] = 'Edit';
            $this->param['top_button'] = route('user.index');
            $this->param['user'] = User::find($id);
            
            return view('backend.user.edit', $this->param);
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
            $updateAdmin = User::find($id);

            $isUnique = $updateAdmin->username == $request->username ? '' : '|unique:users,username';
            $foto = $updateAdmin->profile_photo;

            $this->validate($request, 
                [
                    'nama_lengkap' => 'required|min:6|max:50',
                    'username' => 'required|min:4|max:30|'.$isUnique,
                    'password' => 'required|min:6|confirmed'
                ],
                [
                    'required' => ':attribute harus diisi.',
                    'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                    'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                    'username.min' => 'Minimal panjang karakter 4.',
                    'username.max' => 'Maksimal panjang karakter 30.',
                    'password.min' => 'Minimal panjang karakter 6.',
                    'confirmed' => 'Password tidak sesuai.',
                    'username.unique' => ':attribute telah terdaftar.'
                ],
                [
                    'nama_lengkap' => 'Nama lengkap',
                    'username' => 'Username',
                    'password' => 'Password',
                    'password_confirmation' => 'Konfirmasi password'
                ]
            );

            $updateAdmin->name = $request->get('nama_lengkap');
            $updateAdmin->username = $request->get('username');
            $updateAdmin->password = \Hash::make($request->get('password'));

            if($request->file('photo_profile') != null) {
                return 'halo';
                $folder = 'upload/admin/'.$request->get('username');
                $file = $request->file('photo_profile');
                $filename = date('YmdHis').$file->getClientOriginalName();
                // Get canonicalized absolute pathname
                $path = realpath($folder);

                // If it exist, check if it's a directory
                if(!($path !== true AND is_dir($path)))
                {
                    // Path/folder does not exist then create a new folder
                    mkdir($folder, 0755, true);
                }
                if(file_exists($foto)){
                    if(File::delete($foto)){
                        if($file->move($folder, $filename)) {
                            $updateAdmin->profile_photo = $folder.'/'.$filename;
                        }
                    }
                }
            }
            $updateAdmin->save();
            return redirect('master/user')->withStatus('Berhasil menyimpan data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $user = User::find($id);
            $foto = $user->profile_photo;
            if($foto != null){
                if(file_exists($foto)){
                    if(File::delete($foto)){
                        $user->delete();
                    }
                }
            }
            return redirect()->back()->withStatus('Berhasil menghapus data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }
}

app/Http/Controllers/Backend/CourrierController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Courrier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CourrierController extends Controller
{
    private $param;
    public function __construct()
    {
        $this->param['title'] = 'Kurir';
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->param['subtitle'] = 'List Kurir';
        $this->param['data'] = Courrier::all();
        $this->param['top_button'] = route('courrier.create');

        return view('backend.courrier.index', $this->param);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->param['subtitle'] = 'Tambah Kurir';
        $this->param['top_button'] = route('courrier.index');
        $courrierCode = null;
        $courrier = Courrier::orderBy('courrier_code', 'DESC')->get();
        
        if($courrier->count() > 0){
            $courrierCode = $courrier[0]->courrier_code;

            $lastIncrement = substr($courrierCode, 2);

            $courrierCode = str_pad($lastIncrement + 1, 3, 0, STR_PAD_LEFT);
            $courrierCode = 'CC'.$courrierCode;
            
        }
        else{
            $courrierCode = "CC001";
        }
        $this->param['courrier_code'] = $courrierCode;

        return view('backend.courrier.create', $this->param);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, 
            [
                'courrier_code' => 'required',
                'nama_lengkap' => 'required|min:6|max:50',
                'gender' => 'required',
                'phone' => 'required|min:11|max:13|unique:courrier,phone'
            ],
            [
                'required' => ':attribute harus diisi.',
                'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                'phone.min' => 'Minimal panjang karakter 11',
                'phone.max' => 'Maksimal panjang karakter 13',
                'phone.unique' => ':attribute telah terdaftar.'
            ],
            [
                'courrier_code' => 'Kode Kurir',
                'nama_lengkap' => 'Nama lengkap',
                'gender' => 'Jenis kelamin',
                'phone' => 'Nomor hp'
            ]
        );

        try{
            $newCourrier = new Courrier;
            $newCourrier->courrier_code = $request->get('courrier_code');
            $newCourrier->name = $request->get('nama_lengkap');
            $newCourrier->gender = $request->get('gender');
            $newCourrier->phone = $request->get('phone');
            
            $newCourrier->save();
            return redirect('master/courrier')->withStatus('Berhasil menambah data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($courrierCode)
    {
        try{
            $this->param['subtitle'] = 'Edit';
            $this->param['top_button'] = route('courrier.index');
            $this->param['courrier'] = Courrier::where('courrier_code', $courrierCode)->first();
            
            return view('backend.courrier.edit', $this->param);
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $courrierCode)
    {
        try{
            $courrier = Courrier::where('courrier_code', $courrierCode)->first();

            $isUnique = $courrier->phone == $request->get('phone') ? '' : '|unique:courrier,phone';
            $this->validate($request, 
                [
                    'courrier_code' => 'required',
                    'nama_lengkap' => 'required|min:6|max:50',
                    'gender' => 'required',
                    'phone' => 'required|min:11|max:13|'.$isUnique
                ],
                [
                    'required' => ':attribute harus diisi.',
                    'nama_lengkap.min' => 'Minimal panjang karakter 6.',
                    'nama_lengkap.max' => 'Maksimal panjang karakter 50.',
                    'phone.min' => 'Minimal panjang karakter 11',
                    'phone.max' => 'Maksimal panjang karakter 13',
                    'phone.unique' => ':attribute telah terdaftar.'
                ],
                [
                    'courrier_code' => 'Kode Kurir',
                    'nama_lengkap' => 'Nama lengkap',
                    'gender' => 'Jenis kelamin',
                    'phone' => 'Nomor hp'
                ]
            );
            DB::table('courrier')->where('courrier_code', $courrierCode)->update([
                "courrier_code" => $request->get('courrier_code'),
                "name" => $request->get('nama_lengkap'),
                "gender" => $request->get('gender'),
                "phone" => $request->get('phone')
            ]);

            return redirect('master/courrier')->withStatus('Berhasil menyimpan data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($courrierCode)
    {
        try{
            DB::delete('delete from courrier where courrier_code = ?', [$courrierCode]);
            return redirect()->back()->withStatus('Berhasil menghapus data.');
        }
        catch(\Exception $e){
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return redirect()->back()->withError($e->getMessage());
        }
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        return view('backend.dashboard');
    }
}

resources/views/backend/ingredients/create.blade.php
@extends('backend.layout.master')
@section('content')
<div class="page-wrapper" style="min-height: 250px;">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">{{ $title }}</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">
                        <li><a href="#" class="fw-normal">{{ $title }}/{{ $subtitle }}</a></li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-md-12">
                <div class="white-box">
                    @if (session('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Terjadi kesalahan!</strong>&nbsp;{{ session('error') }}.
                    </div>
                    @endif
                    <h3 class="box-title">{{ $subtitle }}</h3>
                    <a href="{{ $top_button }}" class="btn btn-primary text-white">
                        Lihat Data
                    </a>
                    <form class="mt-4" action="{{ route('ingredients.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="formResep">Resep</label><span class="text-danger">*</span>
                                    <select class="form-control" name="recipe_code" id="formResep">
                                        <option value="0">Pilih Resep</option>
                                        @foreach ($recipe as $item)
                                            <option value="{{ $item->recipe_code }}" @if(old('recipe_code') == $item->recipe_code) selected @endif>{{ ucwords($item->name) }}</option>
                                        @endforeach
                                    </select>
                                    @error('recipe_code')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="formProduct">Bahan</label><span class="text-danger">*</span>
                                    <select class="form-control" name="product_code" id="formProduct">
                                        <option value="0">Pilih Bahan</option>
                                        @foreach ($product as $item)
                                            <option value="{{ $item->product_code }}" @if(old('product_code') == $item->product_code) selected @endif>{{ ucwords($item->name) }}</option>
                                        @endforeach
                                    </select>
                                    @error('product_code')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="formDose">Takaran</label><span class="text-danger">*</span>
                                    <input type="text" class="form-control" id="formNama" name="dose" placeholder="ex : 1 buah" value="{{ old('dose') }}">
                                    @error('dose')
                                    <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="form-inline">
                            <input type="submit" value="Simpan" class="btn btn-success mr-2">
                            <input type="reset" value="Batal" class="btn btn-danger">
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center"> 2021 © Ample Admin brought to you by <a
            href="https://www.wrappixel.com/">wrappixel.com</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
@endsection

resources/views/backend/ingredients/index.blade.php
@extends('backend.layout.master')
@section('content')
<div class="page-wrapper" style="min-height: 250px;">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb bg-white">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">{{ $title }}</h4>
            </div>
            <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                <div class="d-md-flex">
                    <ol class="breadcrumb ms-auto">
                        <li><a href="#" class="fw-normal">{{ $title }}/{{ $subtitle }}</a></li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <div class="row">
            <div class="col-md-12">
                <div class="white-box">
                    @if (session('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Sukses!</strong>&nbsp;{{ session('status') }}
                    </div>
                    @endif
                    @if (session('error'))
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>Terjadi kesalahan!</strong>{{ session('error') }}.
                    </div>
                    @endif
                    <h3 class="box-title">{{ $subtitle }}</h3>
                    <a href="{{ $top_button }}" class="btn btn-primary text-white mb-3">
                        Tambah
                    </a>
                    <table class="table table-xl-responsive mt-4" id="data_table">
                        <thead>
                            <th class="text-center">#</th>
                            <th class="text-center">Nama Resep</th>
                            <th class="text-center">Nama Bahan</th>
                            <th class="text-center">Takaran</th>
                            <th class="text-center">Aksi</th>
                        </thead>
                        <tbody>
                            @forelse ($data as $item)
                            <tr>
                                <td class="text-center">{{ $loop->iteration }}</td>
                                <td class="text-center">{{ ucwords($item->recipe_name) }}</td>
                                <td class="text-center">{{ ucwords($item->product_name) }}</td>
                                <td class="text-center">{{ ucwords($item->dose) }}</td>
                                <td>
                                    <div class="d-flex justify-content-center">
                                        <div class="form-inline p-0">
                                            <a href="{{ route('ingredients.edit', $item->id) }}" class="btn btn-success mr-2" title="Edit" data-toggle="tooltip"> <span class="fa fa-pen"></span> </a>
                                            <form action="{{ route('ingredients.destroy', $item->recipe_code) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                <button type="button" class="btn btn-danger" title="Hapus" data-toggle="tooltip" onclick="confirm('{{ __("Apakah anda yakin ingin menghapus?") }}') ? this.parentElement.submit() : ''">
                                                    <span class="fa fa-minus-circle"></span>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @empty
                                
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <!-- ============================================================== -->
        <!-- End Right sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
    <footer class="footer text-center"> 2021 © Ample Admin brought to you by <a
            href="https://www.wrappixel.com/">wrappixel.com</a>
    </footer>
    <!-- ============================================================== -->
    <!-- End footer -->
    <!-- ============================================================== -->
</div>
<div class="modal modal-show-detail">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          {{-- <h6 class="modal-title">Detail Data</h6> --}}
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body text-center">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">
                <img alt="" id="showDetail" width="100%">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection